<script type="text/javascript" src="../../core/shapeConstants.js"> </script>
<script type="text/javascript" src="../../deps/jquery.min.js"></script>
<script type="text/javascript" src="../../deps/stacktrace.js"></script>
<script type="text/javascript" src="../../core/base/util/shapeUtil.js"> </script>
<script type="text/javascript" src="../../core/soundPubSub.js"> </script>
<script type="text/javascript" src="../../core/eventFactory.js"> </script>
<script type="text/javascript" src="../../core/eventEmitter.js"> </script>
<script type="text/javascript" src="../../core/base/persistence/ObjectRepository.js"> </script>

<script type="text/javascript" src="../../core/shape.js"> </script>
<script type="text/javascript" src="../../core/base/objectTypes/int.js"></script>
<script type="text/javascript" src="../../core/base/objectTypes/function.js"></script>
<script type="text/javascript" src="../../core/base/objectTypes/boolean.js"></script>
<script type="text/javascript" src="../../core/base/objectTypes/collection.js"></script>
<script type="text/javascript" src="../../core/base/objectTypes/string.js"></script>
<script type="text/javascript" src="../../core/base/objectTypes/date.js"></script>
<script type="text/javascript" src="../../core/shapeAttributes.js"> </script>
<script type="text/javascript" src="../../core/DOMCache.js"> </script>
<script type="text/javascript" src="../../core/FunctionReference.js"> </script>
<script type="text/javascript" src="../../core/shapeObjects.js"> </script>
<script type="text/javascript" src="../../core/shapeModels.js"> </script>
<script type="text/javascript" src="../../core/Collection.js"> </script>
<script type="text/javascript" src="../../core/shapeControllers.js"> </script>
<script type="text/javascript" src="../../core/base/shapeExpression.js"> </script>

<script type="text/javascript" src="../../core/base/persistence/BasePersistence.js"> </script>

<!--test suite base models-->
<script type="text/javascript" src="model/testViewModel.js"> </script>
<script type="text/javascript" src="model/testDescription.js"> </script>

<!--working models-->
<script type="text/javascript" src="model/spaghettiMonster.js"> </script>

<script type="text/javascript" src="util/assert.js"> </script>
<script type="text/javascript" src="ctrl/SuiteCtrl.js"> </script>

<!--tests-->
<script type="text/javascript" src="tests/chainTest.js"> </script>
<script type="text/javascript" src="tests/expressionTest.js"> </script>
<script type="text/javascript" src="tests/dateRepositoryTest.js"> </script>

<script type="text/javascript" src="../../core/base/ctrl/button.js"> </script>
<script type="text/javascript" src="../../core/base/ctrl/label.js"> </script>

<script type="text/javascript" src="../../core/base/ctrl/input.js"> </script>
<script type="text/javascript" src="../../core/base/ctrl/ul.js"> </script>
<script type="text/javascript" src="../../core/base/ctrl/component.js"> </script>
<script type="text/javascript" src="../../core/base/ctrl/checkbox.js"> </script>
<script type="text/javascript" src="../../core/base/ctrl/menu.js"> </script>